##Business Understanding

In order to venture into the movie industry successfully, Microsoft's new movie studio needs a clear understanding of the business domain and specific objectives to achieve its goals. Here are the details about the business they intend to enter:

#Business to Venture Into:

Microsoft plans to establish a movie studio to create and distribute original video content. This venture aims to compete in the global entertainment industry by producing movies that resonate with audiences, generate significant box office revenue, and enhance Microsoft's brand presence in the entertainment sector.

#Objectives

To achieve success in this venture, Microsoft's movie studio must set clear and measurable objectives. Here are the primary objectives:

1. To Establish a Profitable Movie Studio

The primary goal is to create a movie studio that generates a substantial profit by producing successful films. Profitability is measured through box office revenue, production cost control, and monetization of content.

2. To Create High-Quality Original Content

The studio aims to produce high-quality and compelling original movies that receive critical acclaim and resonate with diverse audiences. This objective is measured by IMDb ratings, Rotten Tomatoes scores, and awards won.

3. To Maximize Audience Engagement

The studio aims to engage and expand its audience base by catering to the preferences of various demographics. This involves identifying and targeting specific audience segments effectively.

4. To Optimize Investment and Resource Allocation

Efficient resource allocation is crucial. The studio aims to optimize budgets, marketing strategies, and production choices to maximize the return on investment (ROI).

In [1]:

# Importing Libraries
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'seaborn'

In [7]:
# Load the datasets
movie_budgets = pd.read_csv('tn.movie_budgets.csv.gz')
tmdb_movies = pd.read_csv('tmdb.movies.csv.gz')
rt_reviews = pd.read_csv('rt.reviews.tsv.gz', delimiter='\t', encoding='unicode_escape')
rt_movie_info = pd.read_csv('rt.movie_info.tsv.gz', delimiter='\t', encoding='unicode_escape')
bom_movie_gross = pd.read_csv('bom.movie_gross.csv.gz')

# Display the first few rows of each dataset to get an overview
datasets = {
    "Movie Budgets": movie_budgets,
    "TMDB Movies": tmdb_movies,
    "Rotten Tomatoes Reviews": rt_reviews,
    "Rotten Tomatoes Movie Info": rt_movie_info,
    "Box Office Mojo Movie Gross": bom_movie_gross
}
# Let's display the first few rows of each dataset to get an overview

first_rows = {name: df.head() for name, df in datasets.items()}
print(first_rows["Movie Budgets"])
print(first_rows["TMDB Movies"])
print(first_rows["Rotten Tomatoes Reviews"])
print(first_rows["Rotten Tomatoes Movie Info"])
print(first_rows["Box Office Mojo Movie Gross"])

   id  release_date                                        movie  \
0   1  Dec 18, 2009                                       Avatar
1   2  May 20, 2011  Pirates of the Caribbean: On Stranger Tides
2   3   Jun 7, 2019                                 Dark Phoenix
3   4   May 1, 2015                      Avengers: Age of Ultron
4   5  Dec 15, 2017            Star Wars Ep. VIII: The Last Jedi

  production_budget domestic_gross worldwide_gross
0      $425,000,000   $760,507,625  $2,776,345,279
1      $410,600,000   $241,063,875  $1,045,663,875
2      $350,000,000    $42,762,350    $149,762,350
3      $330,600,000   $459,005,868  $1,403,013,963
4      $317,000,000   $620,181,382  $1,316,721,747
   Unnamed: 0            genre_ids     id original_language  \
0           0      [12, 14, 10751]  12444                en
1           1  [14, 12, 16, 10751]  10191                en
2           2        [12, 28, 878]  10138                en
3           3      [16, 35, 10751]    862                en
4           4        [28, 878, 12]  27205                en

                                 original_title  popularity release_date  \
0  Harry Potter and the Deathly Hallows: Part 1      33.533   2010-11-19
1                      How to Train Your Dragon      28.734   2010-03-26
2                                    Iron Man 2      28.515   2010-05-07
3                                     Toy Story      28.005   1995-11-22
4                                     Inception      27.920   2010-07-16

                                          title  vote_average  vote_count
0  Harry Potter and the Deathly Hallows: Part 1           7.7       10788
1                      How to Train Your Dragon           7.7        7610
2                                    Iron Man 2           6.8       12368
3                                     Toy Story           7.9       10174
4                                     Inception           8.3       22186
   id                                             review rating   fresh  \
0   3  A distinctly gallows take on contemporary fina...    3/5   fresh
1   3  It's an allegory in search of a meaning that n...    NaN  rotten
2   3  ... life lived in a bubble in financial dealin...    NaN   fresh
3   3  Continuing along a line introduced in last yea...    NaN   fresh
4   3             ... a perverse twist on neorealism...     NaN   fresh

           critic  top_critic         publisher               date
0      PJ Nabarro           0   Patrick Nabarro  November 10, 2018
1  Annalee Newitz           0           io9.com       May 23, 2018
2    Sean Axmaker           0  Stream on Demand    January 4, 2018
3   Daniel Kasman           0              MUBI  November 16, 2017
4             NaN           0      Cinema Scope   October 12, 2017
   id                                           synopsis rating  \
0   1  This gritty, fast-paced, and innovative police...      R
1   3  New York City, not-too-distant-future: Eric Pa...      R
2   5  Illeana Douglas delivers a superb performance ...      R
3   6  Michael Douglas runs afoul of a treacherous su...      R
4   7                                                NaN     NR

                                 genre          director  \
0  Action and Adventure|Classics|Drama  William Friedkin
1    Drama|Science Fiction and Fantasy  David Cronenberg
2    Drama|Musical and Performing Arts    Allison Anders
3           Drama|Mystery and Suspense    Barry Levinson
4                        Drama|Romance    Rodney Bennett

                            writer  theater_date      dvd_date currency  \
0                   Ernest Tidyman   Oct 9, 1971  Sep 25, 2001      NaN
1     David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $
2                   Allison Anders  Sep 13, 1996  Apr 18, 2000      NaN
3  Paul Attanasio|Michael Crichton   Dec 9, 1994  Aug 27, 1997      NaN
4                     Giles Cooper           NaN           NaN      NaN

  box_office      runtime             studio
0        NaN  104 minutes                NaN
1    600,000  108 minutes  Entertainment One
2        NaN  116 minutes                NaN
3        NaN  128 minutes                NaN
4        NaN  200 minutes                NaN
                                         title studio  domestic_gross  \
0                                  Toy Story 3     BV     415000000.0
1                   Alice in Wonderland (2010)     BV     334200000.0
2  Harry Potter and the Deathly Hallows Part 1     WB     296000000.0
3                                    Inception     WB     292600000.0
4                          Shrek Forever After   P/DW     238700000.0

  foreign_gross  year
0     652000000  2010
1     691300000  2010
2     664300000  2010
3     535700000  2010
4     513900000  2010

In [8]:
#Display column and rows each dataset to get an overview
dataset_shapes = {name: df.shape for name, df in datasets.items()}
dataset_shapes

{'Movie Budgets': (5782, 6),
 'TMDB Movies': (26517, 10),
 'Rotten Tomatoes Reviews': (54432, 8),
 'Rotten Tomatoes Movie Info': (1560, 12),
 'Box Office Mojo Movie Gross': (3387, 5)}

In [9]:
# Find info like column names, non-null counts, datatypes, 
for name, df in datasets.items():
    print(f"Info for {name}:")
    print("-" * 40)
    print(df.info())
    print("\n\n")

Info for Movie Budgets:
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5782 entries, 0 to 5781
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5782 non-null   int64
 1   release_date       5782 non-null   object
 2   movie              5782 non-null   object
 3   production_budget  5782 non-null   object
 4   domestic_gross     5782 non-null   object
 5   worldwide_gross    5782 non-null   object
dtypes: int64(1), object(5)
memory usage: 271.2+ KB
None



Info for TMDB Movies:
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         26517 non-null  int64
 1   genre_ids          26517 non-null  object
 2   id                 26517 non-null  int64
 3   original_language  26517 non-null  object
 4   original_title     26517 non-null  object
 5   popularity         26517 non-null  float64
 6   release_date       26517 non-null  object
 7   title              26517 non-null  object
 8   vote_average       26517 non-null  float64
 9   vote_count         26517 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB
None



Info for Rotten Tomatoes Reviews:
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54432 entries, 0 to 54431
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          54432 non-null  int64
 1   review      48869 non-null  object
 2   rating      40915 non-null  object
 3   fresh       54432 non-null  object
 4   critic      51710 non-null  object
 5   top_critic  54432 non-null  int64
 6   publisher   54123 non-null  object
 7   date        54432 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.3+ MB
None



Info for Rotten Tomatoes Movie Info:
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1560 non-null   int64
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB
None



Info for Box Office Mojo Movie Gross:
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB
None

In [11]:
#Display Descriptive Statitics about the Datasets 
for name, df in datasets.items():
    print(f"Descriptive Statistics for {name}:")
    print("-" * 60)
    print(df.describe(include='all'))
    print("\n\n")

Descriptive Statistics for Movie Budgets:
------------------------------------------------------------
                 id  release_date      movie production_budget domestic_gross  \
count   5782.000000          5782       5782              5782           5782
unique          NaN          2418       5698               509           5164
top             NaN  Dec 31, 2014  Halloween       $20,000,000             $0
freq            NaN            24          3               231            548
mean      50.372363           NaN        NaN               NaN            NaN
std       28.821076           NaN        NaN               NaN            NaN
min        1.000000           NaN        NaN               NaN            NaN
25%       25.000000           NaN        NaN               NaN            NaN
50%       50.000000           NaN        NaN               NaN            NaN
75%       75.000000           NaN        NaN               NaN            NaN
max      100.000000           NaN        NaN               NaN            NaN

       worldwide_gross
count             5782
unique            5356
top                 $0
freq               367
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN



Descriptive Statistics for TMDB Movies:
------------------------------------------------------------
         Unnamed: 0 genre_ids             id original_language original_title  \
count   26517.00000     26517   26517.000000             26517          26517
unique          NaN      2477            NaN                76          24835
top             NaN      [99]            NaN                en           Eden
freq            NaN      3700            NaN             23291              7
mean    13258.00000       NaN  295050.153260               NaN            NaN
std      7654.94288       NaN  153661.615648               NaN            NaN
min         0.00000       NaN      27.000000               NaN            NaN
25%      6629.00000       NaN  157851.000000               NaN            NaN
50%     13258.00000       NaN  309581.000000               NaN            NaN
75%     19887.00000       NaN  419542.000000               NaN            NaN
max     26516.00000       NaN  608444.000000               NaN            NaN

          popularity release_date  title  vote_average    vote_count
count   26517.000000        26517  26517  26517.000000  26517.000000
unique           NaN         3433  24688           NaN           NaN
top              NaN   2010-01-01   Eden           NaN           NaN
freq             NaN          269      7           NaN           NaN
mean        3.130912          NaN    NaN      5.991281    194.224837
std         4.355229          NaN    NaN      1.852946    960.961095
min         0.600000          NaN    NaN      0.000000      1.000000
25%         0.600000          NaN    NaN      5.000000      2.000000
50%         1.374000          NaN    NaN      6.000000      5.000000
75%         3.694000          NaN    NaN      7.000000     28.000000
max        80.773000          NaN    NaN     10.000000  22186.000000



Descriptive Statistics for Rotten Tomatoes Reviews:
------------------------------------------------------------
                  id                   review rating  fresh        critic  \
count   54432.000000                    48869  40915  54432         51710
unique           NaN                    48682    186      2          3496
top              NaN  Parental Content Review    3/5  fresh  Emanuel Levy
freq             NaN                       24   4327  33035           595
mean     1045.706882                      NaN    NaN    NaN           NaN
std       586.657046                      NaN    NaN    NaN           NaN
min         3.000000                      NaN    NaN    NaN           NaN
25%       542.000000                      NaN    NaN    NaN           NaN
50%      1083.000000                      NaN    NaN    NaN           NaN
75%      1541.000000                      NaN    NaN    NaN           NaN
max      2000.000000                      NaN    NaN    NaN           NaN

          top_critic        publisher             date
count   54432.000000            54123            54432
unique           NaN             1281             5963
top              NaN  eFilmCritic.com  January 1, 2000
freq             NaN              673             4303
mean        0.240594              NaN              NaN
std         0.427448              NaN              NaN
min         0.000000              NaN              NaN
25%         0.000000              NaN              NaN
50%         0.000000              NaN              NaN
75%         0.000000              NaN              NaN
max         1.000000              NaN              NaN



Descriptive Statistics for Rotten Tomatoes Movie Info:
------------------------------------------------------------
                 id                                           synopsis rating  \
count   1560.000000                                               1498   1557
unique          NaN                                               1497      6
top             NaN  A group of air crash survivors are stranded in...      R
freq            NaN                                                  2    521
mean    1007.303846                                                NaN    NaN
std      579.164527                                                NaN    NaN
min        1.000000                                                NaN    NaN
25%      504.750000                                                NaN    NaN
50%     1007.500000                                                NaN    NaN
75%     1503.250000                                                NaN    NaN
max     2000.000000                                                NaN    NaN

        genre          director       writer theater_date     dvd_date  \
count    1552              1361         1111         1201         1201
unique    299              1125         1069         1025          717
top     Drama  Steven Spielberg  Woody Allen  Jan 1, 1987  Jun 1, 2004
freq      151                10            4            8           11
mean      NaN               NaN          NaN          NaN          NaN
std       NaN               NaN          NaN          NaN          NaN
min       NaN               NaN          NaN          NaN          NaN
25%       NaN               NaN          NaN          NaN          NaN
50%       NaN               NaN          NaN          NaN          NaN
75%       NaN               NaN          NaN          NaN          NaN
max       NaN               NaN          NaN          NaN          NaN

       currency box_office     runtime              studio
count       340        340        1530                 494
unique        1        336         142                 200
top           $    600,000  90 minutes  Universal Pictures
freq        340          2          72                  35
mean        NaN        NaN         NaN                 NaN
std         NaN        NaN         NaN                 NaN
min         NaN        NaN         NaN                 NaN
25%         NaN        NaN         NaN                 NaN
50%         NaN        NaN         NaN                 NaN
75%         NaN        NaN         NaN                 NaN
max         NaN        NaN         NaN                 NaN



Descriptive Statistics for Box Office Mojo Movie Gross:
------------------------------------------------------------
            title studio  domestic_gross foreign_gross         year
count        3387   3382    3.359000e+03          2037  3387.000000
unique       3386    257             NaN          1204          NaN
top     Bluebeard    IFC             NaN       1200000          NaN
freq            2    166             NaN            23          NaN
mean          NaN    NaN    2.874585e+07           NaN  2013.958075
std           NaN    NaN    6.698250e+07           NaN     2.478141
min           NaN    NaN    1.000000e+02           NaN  2010.000000
25%           NaN    NaN    1.200000e+05           NaN  2012.000000
50%           NaN    NaN    1.400000e+06           NaN  2014.000000
75%           NaN    NaN    2.790000e+07           NaN  2016.000000
max           NaN    NaN    9.367000e+08           NaN  2018.000000

In [12]:
#Cleaning the Datasets 

# Check if any dataset has missing values
missing_values_check = {name: df.isnull().values.any() for name, df in datasets.items()}
missing_values_check

{'Movie Budgets': False,
 'TMDB Movies': False,
 'Rotten Tomatoes Reviews': True,
 'Rotten Tomatoes Movie Info': True,
 'Box Office Mojo Movie Gross': True}

In [15]:
# 1. Handling missing values for Rotten Tomatoes Reviews
rt_reviews['review'].fillna('Unknown', inplace=True)
rt_reviews['rating'].fillna(rt_reviews['rating'].mode()[0], inplace=True)
rt_reviews['critic'].fillna('Unknown', inplace=True)
rt_reviews['publisher'].fillna('Unknown', inplace=True)

# 2. Handling missing values for Rotten Tomatoes Movie Info
rt_movie_info['rating'].fillna(rt_movie_info['rating'].mode()[0], inplace=True)
rt_movie_info['genre'].fillna(rt_movie_info['genre'].mode()[0], inplace=True)
# For the currency column, we'll use "Unknown" as a placeholder
rt_movie_info['currency'].fillna('Unknown', inplace=True)

# 3. Handling missing values for Box Office Mojo Movie Gross
# Convert only the non-NaN values in 'foreign_gross' to strings, then remove commas and convert to float
bom_movie_gross['foreign_gross'] = bom_movie_gross['foreign_gross'].dropna().astype(str).str.replace(',', '').astype(float)
bom_movie_gross['studio'].fillna('Unknown', inplace=True)
bom_movie_gross['domestic_gross'].fillna(bom_movie_gross['domestic_gross'].median(), inplace=True)
bom_movie_gross['foreign_gross'].fillna(bom_movie_gross['foreign_gross'].median(), inplace=True)

# Check for any remaining missing values
remaining_missing_values = {name: df.isnull().sum() for name, df in datasets.items() if df.isnull().values.any()}
remaining_missing_values

{'Rotten Tomatoes Movie Info': id                 0
 synopsis          62
 rating             0
 genre              0
 director         199
 writer           449
 theater_date     359
 dvd_date         359
 currency           0
 box_office      1220
 runtime           30
 studio          1066
 dtype: int64}

##Univariate EDA 
This helps use analyze the distribution of certain key variables within each dataset. Potential analyses include:
•	Distribution of movie release dates (Dataset: Movie Budgets)
•	Distribution of movie ratings (Dataset: TMDB Movies)
•	Distribution of movie genres (Dataset: Rotten Tomatoes Movie Info)

##Bivariate EDA
Once we understand individual variables, we can analyze the relationships between two variables. Some potential analyses here include:
•	Relationship between production budget and worldwide gross
•	Correlation between movie ratings and box office performance
•	Comparing domestic vs. foreign gross for movies

##Multivariate EDA
For this analysis, we'll investigate the combined impact of multiple variables on a specific outcome. Given the datasets and our objective, the following multivariate analysis options are recommended:
Genre, Ratings, and Box Office Gross:
•	Datasets: "TMDB Movies" and "Box Office Mojo Movie Gross" or "Movie Budgets".
•	Goal: Understanding how genres and ratings together influence box office performance can offer insights into which combinations are most profitable.
•	Visualization: A heatmap or stacked bar chart that shows average gross earnings for each genre, further segmented by rating brackets (e.g., 0-2, 2-4, ... 8-10).
Production Budget, Ratings, and Worldwide Gross:
•	Datasets: "Movie Budgets" and "TMDB Movies".
•	Goal: By analyzing the interplay between production budget, movie ratings, and worldwide gross, we can assess the profitability of movies at various budget levels and ratings.
•	Visualization: A scatter plot with production budget on the x-axis, worldwide gross on the y-axis, and points colored by rating.
Director, Ratings, and Box Office Gross:
•	Datasets: "TMDB Movies" and "Rotten Tomatoes Movie Info".
•	Goal: Certain directors might consistently produce highly-rated movies that also perform well at the box office. Identifying these directors can be valuable for future projects and potential partnerships. 
•	Visualization: A scatter plot with directors on the x-axis, average gross on the y-axis, and points sized by average rating.

In [17]:
#Univariate EDA
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Distribution of movie release dates
movie_budgets['release_date'] = pd.to_datetime(movie_budgets['release_date'])
plt.figure(figsize=(12, 6))
movie_budgets['release_date'].dt.year.value_counts().sort_index().plot(kind='bar')
plt.title('Distribution of Movie Release Dates')
plt.xlabel('Year')
plt.ylabel('Number of Movies')
plt.show()

# 2. Distribution of movie ratings
plt.figure(figsize=(12, 6))
tmdb_movies['vote_average'].hist(bins=20)
plt.title('Distribution of Movie Ratings')
plt.xlabel('Rating')
plt.ylabel('Number of Movies')
plt.show()

# 3. Distribution of movie genres
# Split the genres and count each genre occurrence
genres = rt_movie_info['genre'].str.split('|').explode().value_counts()
plt.figure(figsize=(12, 6))
genres.plot(kind='bar')
plt.title('Distribution of Movie Genres')
plt.xlabel('Genre')
plt.ylabel('Number of Movies')
plt.show()

ModuleNotFoundError: No module named 'seaborn'